name: C/C++ CI

on: push

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build library
      run: make lib
    - name: Run tests
      run: make test

  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build library
      run: make lib
    - name: Run tests
      run: make test

