name: "Doc build"
on: push

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: apt installs
      run: sudo apt-get install -y plantuml doxygen
    - name: pip installs
      run: pip install -r docs/requirements.txt
    - name: Build doxygen documentation
      run: make -C docs doxygen
    - name: Build sphinx documentation
      run: make -C docs html
    - uses: actions/upload-artifact@v2
      with:
        name: DocumentationHTML
        path: docs/build/html/
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/build/html/